name: Generate site + javadoc github pages

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write     # to deploy to Pages
  id-token: write  # to verify the deployment originates from an appropriate source

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'

      - name: Generate sites (project info and javadoc) for whole project
        run: mvn -B clean site site:stage

      - name: Merge module sites into parent site
        run: |
          cp -r target/site site
          mkdir site/modules
          cp -r modules/mpgaai-shhaa/target/site site/modules/mpgaai-shhaa
          cp -r modules/mpgaai-jaas/target/site site/modules/mpgaai-jaas

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    
